### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [Divested-Mobile/IRRemote#1]
Could you please submit this to F-Droid? There is no IR remote in F-Droid currently. This would be very useful. Thanks!

**Comment by SkewedZeppelin** [comment]
I will try to do it along with the others.

**Comment by linsui** [comment]
Thanks!

**Comment by SkewedZeppelin** [comment]
@twinone 
Hello :wave: 
I made this fork of your `Universal TV Remote` app back in 2018.
It removes all of the proprietary bits and "anti-features".

Are you OK with both the existence of this fork and the publishing of this app on F-Droid repository?

**Comment by twinone** [comment]
@SkewedZeppelin Fine with me :)

**Comment by linsui** [comment]
Already available on F-Droid :)
