### ISSUE TITLE
Database buttons with custom name

### ISSUE THREAD

**Issue by Slion** [Divested-Mobile/IRRemote#11]
Can I add a button in the database with a custom name somehow?
If the file name does not match an id it just sets `?` as a label.
If I put some text instead of an integer in the button file name it crashes.

**Comment by SkewedZeppelin** [comment]
All buttons are hardcoded and need to be added first.

**Comment by Biswa96** [comment]
Could you provide any example? It is possible to add custom buttons in a remote but I am not sure if it works.

**Comment by Slion** [comment]
This will be possible once #12 is merged.
