### ISSUE TITLE
Remote switch not applied

### ISSUE THREAD

**Issue by Slion** [Divested-Mobile/IRRemote#13]
When you switch to a remote it is not applied.
You can still see the remote that was previously loaded.
You need to go to edit and then come back for the remote switch to be applied.

Huawei P30 Pro - Android 10 - v1.7.0
Also reproduceable from the tip of `libre`.

**Comment by Biswa96** [comment]
This is a core issue and present since beginning. The issue is being tracked here https://gitlab.com/divested-mobile/irremote/-/issues/22
