### ISSUE TITLE
Remove ads area

### ISSUE THREAD

**Issue by xmha97** [Divested-Mobile/IRRemote#2]
Hi, there is a rectangle at the bottom of the app that I think is for display ads, please delete it.
![IMG_20211013_035631_505.jpg](https://user-images.githubusercontent.com/23485114/137047054-04545771-9a31-4530-8d8b-dcef22bc3f2a.jpg)

**Comment by SkewedZeppelin** [comment]
Nice catch, thanks!

I've pushed a new build to my F-Droid repository and it should be on the official F-Droid repository in a few days.

**Comment by xmha97** [comment]
Thanks.
